import os
import json
import boto3
from datetime import datetime

client = boto3.client('ses')
from_email = os.environ['from_email']
to_email = os.environ['to_email']

def lambda_handler(event, context):
    CHARSET = "UTF-8"
    
    # Extracting some event information for the email content
    event_details = json.dumps(event, indent=4)
    current_time = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
    
    # Updated email body
    body_html = f"""
    <html>
    <body>
        <h1>Notification from AWS Lambda</h1>
        <p><strong>Triggered Event Details:</strong></p>
        <pre>{event_details}</pre>
        <p>This email was generated by an AWS Lambda function.</p>
        <hr/>
        <footer>
            <p>Sent at: {current_time}</p>
            <p>From: AWS Lambda & SES Integration</p>
        </footer>
    </body>
    </html>
    """
    
    # Sending email via SES
    ses_response = client.send_email(
        Destination={
            "ToAddresses": [
                to_email,
            ],
        },
        Message={
            "Body": {
                "Html": {
                    "Charset": CHARSET,
                    "Data": body_html,
                }
            },
            "Subject": {
                "Charset": CHARSET,
                "Data": "AWS Lambda Notification",
            },
        },
        Source=from_email
    )
    
    print("SES response ID is: " + ses_response["MessageId"])
